name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  init:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Cache node_modules
      #   uses: actions/cache@v3
      #   with:
      #     path: frontend/node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install --no-frozen-lockfile

      # - name: List frontend directory
      #   run: ls -la
      #   working-directory: frontend

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Restore node_modules from cache
      #   uses: actions/cache@v3
      #   with:
      #     path: frontend/node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install pnpm
        run: npm install -g pnpm

      # - name: List frontend directory contents
      #   run: ls -la
      #   working-directory: frontend

      - name: Build the app
        working-directory: frontend
        run: pnpm run build
        env:
          NODE_OPTIONS: --max-old-space-size=3584
